language: c++
compiler: g++-5.4

script: ./configure && make

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get -qq update
  - sudo apt-get -qq install gcc-5
  - sudo apt-get -qq install automake
  - g++ -v

matrix:
    include:
        os: linux
        addons:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
          - automake
        env:
          - MATRIX_EVAL="CC=gcc && CXX=g++"
