language: c++
compiler: g++-5.4

script: ./configure && make

before_install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 100

addons:
    apt:
        packages:
          - gcc-5
          - automake

matrix:
    include:
        os: linux
        addons:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
          - automake
           - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 100
        env:
          - COMPILER=g++-5
          - CC=gcc=5
          - CXX=g++-5
