language: c++
compiler: g++-5.4

script: ./configure && make

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get -qq update

addons:
    apt:
        packages:
          - gcc-5
          - automake

matrix:
    include:
        os: linux
        addons:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
          - automake
        env:
          - COMPILER=g++-5
          - CC=gcc=5
          - CXX=g++-5
