language: c++
compiler: g++
sudo: required
dist: trusty

before_install:
  # Neccessary repo for g++-5
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  # Update the sources
  - sudo apt-get update -qq

install:
  # install g++5
  - sudo apt-get install -qq g++-5
  # use g++5 instead of the default g++
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 100

before_script:
  # prevent aclocal timestamp errors
  - touch configure.ac aclocal.m4 configure Makefile.am Makefile.in

 # custom make script because makefile does not have target test
script: ./configure && make

 # setup environment varriables
matrix:
    include:
        os: linux
        env:
          - COMPILER=g++-5
          - CC=gcc+5
          - CXX=g++-5
