language: c++
compiler: g++
dist: xenial

script: ./configure && make

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 100

matrix:
    include:
        os: linux
        env:
          - COMPILER=g++-5
          - CC=gcc=5
          - CXX=g++-5
