language: c++
compiler: g++-5.4

script: ./configure && make

matrix:
    include:
        os: linux
        addons:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5.4
          - aclocal-1.15
        env:
          - MATRIX_EVAL="CC=gcc-5.4 && CXX=g++-5.4"
