language: c++
compiler: g++
dist: xenial

script: ./configure && make

before_install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 100

matrix:
    include:
        os: linux
        addons:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
          - automake
        sources:
          - ubuntu-toolchain-r-test
        env:
          - COMPILER=g++-5
          - CC=gcc=5
          - CXX=g++-5
